export const SET_HEADER_CARD = "SET_HEADER_CARD";
export const SET_PRODUCTS = "SET_PRODUCTS";
export const FETCH_PRODUCTS_SUCCESS = "SET_PRODUCTS";

export const UPDATE_STATUS = "UPDATE_STATUS";


export const SET_EMPLOYEES = "SET_EMPLOYEES";
export const FETCH_EMPLOYEES_SUCCESS = "FETCH_EMPLOYEES_SUCCESS";
export const UPDATE_EMPLOYEE_STATUS = "UPDATE_EMPLOYEE_STATUS";